import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, FileText, Lightbulb, Menu, Sigma, Upload, Variable } from "lucide-react";
import { SolverShell } from "@/components/solver/solver-shell";
import { MathDisplay } from "@/components/math/math-display";

type Variant = "calculus" | "algebra";

const calculusTools = [
  ["Derivative Solver", "Find derivatives step by step.", "/derivative-calculator", "\\frac{d}{dx}"],
  ["Integral Solver", "Compute indefinite and definite integrals.", "/integral-calculator", "\\int"],
  ["Limit Solver", "Evaluate limits and one-sided limits.", "/limit-calculator", "\\lim"],
  ["Series Solver", "Work with infinite series and sequences.", "/calculus-calculator", "\\sum"],
  ["Equation Solver", "Solve differential and standard equations.", "/equation-solver", "y''"],
  ["Algebra Solver", "Solve equations and algebra problems.", "/algebra-solver", "x"],
] as const;
const algebraTools = [
  ["Equation Solver", "Solve linear and nonlinear equations.", "/equation-solver", "x=?"],
  ["Simplify Expressions", "Combine terms and reduce expressions.", "/simplify-calculator", "a+b"],
  ["Factor Polynomials", "Factor quadratics and polynomials.", "/factoring-calculator", "(x-a)"],
  ["Quadratic Solver", "Find roots with clear working.", "/quadratic-solver", "x^2"],
  ["Systems of Equations", "Solve related equations together.", "/algebra-solver", "\\{x,y\\}"],
  ["Fraction Calculator", "Work with rational expressions.", "/fraction-calculator", "\\frac{a}{b}"],
] as const;

function EditorialHeader({ active }: { active: Variant }): React.JSX.Element {
  return <header className="sticky top-0 z-40 border-b border-[#dbe5f4] bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1240px] items-center px-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-3 font-bold text-[#071f4a]"><span className="font-serif text-4xl italic leading-none text-[#0967ed]">∫</span><span>Calculus Solver</span></Link><nav className="mx-auto hidden h-full items-center gap-10 md:flex" aria-label="Main navigation"><Link href="/calculus-solver" className={`flex h-full items-center border-b-2 text-sm ${active === "calculus" ? "border-[#0967ed] text-[#0967ed]" : "border-transparent text-[#314567]"}`}>Calculus</Link><Link href="/algebra-solver" className={`flex h-full items-center border-b-2 text-sm ${active === "algebra" ? "border-[#0967ed] text-[#0967ed]" : "border-transparent text-[#314567]"}`}>Algebra Solver</Link><Link href="/calculus-calculator" className="text-sm text-[#314567]">Calculators</Link><Link href="/examples" className="text-sm text-[#314567]">Examples</Link><Link href="/guides" className="text-sm text-[#314567]">Guides</Link></nav><Link href="/about" className="hidden rounded-lg border border-[#82aff5] px-5 py-2 text-sm text-[#0967ed] sm:block">About</Link><details className="relative ml-auto md:hidden"><summary className="flex h-10 w-10 cursor-pointer list-none items-center justify-center rounded-lg border border-[#dbe5f4]"><Menu className="h-5 w-5" /></summary><div className="absolute right-0 top-12 w-56 rounded-xl border border-[#dbe5f4] bg-white p-2 shadow-xl"><Link className="block rounded-lg p-3" href="/calculus-solver">Calculus</Link><Link className="block rounded-lg p-3" href="/algebra-solver">Algebra Solver</Link><Link className="block rounded-lg p-3" href="/calculus-calculator">Calculators</Link><Link className="block rounded-lg p-3" href="/examples">Examples</Link></div></details></div></header>;
}

function EditorialFooter(): React.JSX.Element {
  return <footer className="mt-16 bg-[#061f49] text-white"><div className="mx-auto grid max-w-[1240px] gap-8 px-4 py-10 sm:grid-cols-2 sm:px-6 lg:grid-cols-5 lg:px-8"><div><p className="font-serif text-xl">∫ &nbsp;Calculus Solver</p><p className="mt-3 text-xs leading-5 text-blue-100/70">Solve math problems step by step and understand the process.</p></div>{[["Solvers", ["Derivative Solver", "Integral Solver", "Limit Solver"]], ["Guides", ["Calculus Basics", "Derivatives", "Integrals"]], ["Examples", ["Popular Examples", "Practice Problems", "By Topic"]], ["Legal", ["Terms of Use", "Privacy Policy", "Disclaimer"]]].map(([title, links]) => <div key={title as string}><h2 className="text-sm font-bold">{title}</h2><ul className="mt-3 space-y-2 text-xs text-blue-100/75">{(links as string[]).map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div></footer>;
}

export function SolverLandingPage({ variant }: { variant: Variant }): React.JSX.Element {
  const algebra = variant === "algebra";
  const tools = algebra ? algebraTools : calculusTools;
  const examples = algebra ? ["2x + 5 = 17", "x² − 5x + 6 = 0", "factor x² − 9", "simplify 3x + 2x − 4", "2x + y = 7, x − y = 2", "(x² − 1)/(x − 1)"] : ["∫ x² cos(x) dx", "lim x→∞ (1 + 1/x)ˣ", "d/dx (x³ sin(x))", "d/dx ln(x)", "lim x→0 sin(x)/x", "∫ eˣ cos(x) dx"];
  const faqs = algebra ? ["Is the Algebra Solver free to use?", "Can it show every algebra step?", "Can it solve quadratic equations?", "Does it simplify and factor expressions?", "Can I use it for homework practice?"] : ["Is Calculus Solver free to use?", "Do I need to create an account?", "Can I upload a photo of my problem?", "What types of calculus problems can it solve?", "Are the solutions suitable for homework and exams?"];
  const heroTitle = algebra ? "Solve Algebra Problems\nStep by Step" : "Solve Calculus Problems\nStep by Step";
  const heroText = algebra ? "Enter an equation, expression, polynomial, or system and get a clear solution with every algebra step explained." : "Enter a derivative, integral, limit, or series problem and get a clear solution with every step explained.";
  return <div className="min-h-screen bg-[radial-gradient(circle_at_50%_0%,#ffffff_0%,#f8fbff_50%,#f1f6fd_100%)] text-[#071f4a]"><EditorialHeader active={variant} />
    <main id="main-content" tabIndex={-1} className="focus-visible:outline-none">
      <section className="mx-auto max-w-[1240px] px-4 pb-10 pt-12 text-center sm:px-6 lg:px-8"><h1 className="whitespace-pre-line font-serif text-5xl leading-[.98] tracking-[-.025em] sm:text-6xl">{heroTitle}</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-[#5f6f8d]">{heroText}</p><p className="mt-3 text-sm font-medium text-[#0967ed]">Free &nbsp;•&nbsp; No sign-up &nbsp;•&nbsp; Instant results</p><div className="mt-8 rounded-2xl border border-[#d9e4f3] bg-white p-3 text-left shadow-[0_16px_45px_rgba(35,74,132,.13)] sm:p-6"><SolverShell mode={algebra ? "algebra" : "auto"} /></div></section>
      <section className="border-y border-[#e0e9f5] bg-white/70"><div className="mx-auto grid max-w-[1100px] gap-8 px-4 py-10 md:grid-cols-[250px_1fr] md:items-center"><div><h2 className="font-serif text-3xl leading-tight">Clear answers, not just final answers</h2><p className="mt-5 text-sm leading-7 text-[#5f6f8d]">See every step so you can learn the method, check your work, and understand the result.</p></div><div className="rounded-xl border border-[#d9e4f3] bg-white p-6 shadow-sm"><p className="font-bold">Example: <span className="font-mono font-normal">{algebra ? "x² − 5x + 6 = 0" : "∫ x² · cos(x) dx"}</span></p><ol className="mt-5 space-y-3 text-sm text-[#314567]">{(algebra ? ["Move every term to one side.", "Factor the polynomial as (x − 2)(x − 3).", "Set each factor to zero: x = 2 or x = 3."] : ["Choose integration by parts.", "Apply the rule and integrate again.", "Simplify the terms and add the constant C."]).map((step, i) => <li key={step} className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#0967ed] text-xs font-bold text-white">{i + 1}</span>{step}</li>)}</ol></div></div></section>
      <section className="mx-auto max-w-[1140px] px-4 py-12"><h2 className="text-center font-serif text-3xl">Choose What You Want to Solve</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tools.map(([title, text, href, latex]) => <Link key={title} href={href} className="group flex min-h-28 items-center gap-5 rounded-xl border border-[#d9e4f3] bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-[#91b9f5] hover:shadow-lg"><span className="w-12 shrink-0 text-center font-serif text-3xl text-[#0967ed]"><MathDisplay latex={String.raw`${latex}`} display="inline" /></span><span><strong className="block">{title}</strong><span className="mt-1 block text-xs leading-5 text-[#5f6f8d]">{text}</span></span><ArrowRight className="ml-auto h-4 w-4 text-[#0967ed]" /></Link>)}</div></section>
      <section className="border-y border-[#e0e9f5] bg-white/75"><div className="mx-auto max-w-[1080px] px-4 py-10"><h2 className="text-center font-serif text-3xl">How {algebra ? "Algebra Solver" : "Calculus Solver"} Works</h2><div className="mt-8 grid gap-8 sm:grid-cols-3">{[[Upload, "Enter your problem", "Type, use the math keyboard, or upload a problem."], [FileText, "Review each step", "Get a clear solution explained in plain language."], [Lightbulb, "Understand the result", "Build confidence and apply the method again."]].map(([Icon, title, text], i) => { const StepIcon = Icon as typeof Upload; return <div key={title as string} className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-50 font-bold text-[#0967ed]">{i + 1}</span><StepIcon className="h-7 w-7 shrink-0 text-[#0967ed]" /><div><h3 className="font-bold">{title as string}</h3><p className="mt-2 text-xs leading-5 text-[#5f6f8d]">{text as string}</p></div></div>})}</div></div></section>
      <section className="mx-auto max-w-[1080px] px-4 py-12"><h2 className="text-center font-serif text-3xl">Popular {algebra ? "Algebra" : "Calculus"} Examples</h2><div className="mt-7 grid overflow-hidden rounded-xl border border-[#d9e4f3] bg-white sm:grid-cols-2">{examples.map((example) => <Link key={example} href={`/${algebra ? "algebra-solver" : "calculus-solver"}?q=${encodeURIComponent(example)}`} className="flex items-center justify-between border-b border-[#d9e4f3] p-4 font-mono text-sm last:border-b-0 sm:border-r"><span>{example}</span><ArrowRight className="h-4 w-4" /></Link>)}</div></section>
      <section className="border-y border-[#e0e9f5] bg-white/70"><div className="mx-auto grid max-w-[1080px] gap-8 px-4 py-10 md:grid-cols-2 md:items-center"><div><h2 className="font-serif text-3xl">Built for Learning, Homework, and Verification</h2><p className="mt-4 text-sm leading-7 text-[#5f6f8d]">Each solution is broken into clear steps so you can see the “why” behind every move. Use it to learn, verify your work, and prepare with confidence.</p><div className="mt-5 flex flex-wrap gap-4 text-xs font-semibold text-[#0967ed]"><span className="flex items-center gap-1"><CheckCircle2 className="h-4 w-4" /> Explainable</span><span className="flex items-center gap-1"><BookOpen className="h-4 w-4" /> Learning focused</span><span className="flex items-center gap-1"><Variable className="h-4 w-4" /> Symbolic math</span></div></div><div className="rounded-xl border border-[#d9e4f3] bg-[#f8fbff] p-7 text-center"><Sigma className="mx-auto h-8 w-8 text-[#0967ed]" /><p className="mt-4 font-serif text-2xl">{algebra ? "Method + reasoning = confidence" : "Rules + steps = understanding"}</p></div></div></section>
      <section className="mx-auto max-w-[1080px] px-4 py-12"><h2 className="text-center font-serif text-3xl">Frequently Asked Questions</h2><div className="mt-6 divide-y divide-[#d9e4f3] rounded-xl border border-[#d9e4f3] bg-white">{faqs.map((faq) => <details key={faq} className="px-5 py-4"><summary className="cursor-pointer list-none text-sm font-semibold after:float-right after:content-['›']">{faq}</summary><p className="mt-3 text-sm leading-6 text-[#5f6f8d]">Yes. The solver is designed to provide clear, accessible help with detailed steps and no account required.</p></details>)}</div></section>
    </main><EditorialFooter /></div>;
}
