import type { Metadata } from "next";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of service for Calculus Solver."
};

export default function TermsPage(): React.JSX.Element {
  return (
    <>
      <Header />
      <main className="mx-auto w-full max-w-content px-4 py-10 sm:px-6 lg:px-8">
        <h1 className="text-4xl font-bold tracking-tight text-heading">Terms of Service</h1>
        <div className="prose mt-8 max-w-none text-body">
          <p>
            By using Calculus Solver, you agree to these terms. The service is provided as an educational tool and is
            not a substitute for professional mathematical advice.
          </p>
          <h2 className="mt-6 text-xl font-semibold text-heading">Acceptable Use</h2>
          <p>
            Do not use the service to process malicious, illegal, or harmful content. The input field is for mathematical
            problems only.
          </p>
          <h2 className="mt-6 text-xl font-semibold text-heading">Accuracy</h2>
          <p>
            Results may be generated by AI or local symbolic engines. Always verify important answers independently.
          </p>
          <h2 className="mt-6 text-xl font-semibold text-heading">Changes</h2>
          <p>We may update these terms at any time. Continued use of the service constitutes acceptance of the changes.</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
