import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata({
  title: "Terms of Service",
  description: "Terms of service for Calculus Solver.",
  path: "/terms",
  keywords: ["terms of service", "user agreement", "Calculus Solver terms"]
});

const lastUpdated = "July 8, 2026";

export default function TermsPage(): React.JSX.Element {
  return (
    <>
      <Header />
      <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-content px-4 py-10 sm:px-6 lg:px-8 focus-visible:outline-none">
        <h1 className="text-4xl font-bold tracking-tight text-heading">Terms of Service</h1>
        <p className="mt-2 text-sm text-body">Last updated: {lastUpdated}</p>
        <div className="prose mt-8 max-w-none text-body">
          <p>
            By using Calculus Solver, you agree to these terms. The service is provided as an
            educational tool and is not a substitute for professional mathematical advice.
          </p>

          <h2 className="mt-6 text-xl font-semibold text-heading">Service Description</h2>
          <p>
            Calculus Solver interprets natural-language and symbolic math input, then returns
            step-by-step solutions, graphs, and verification notes. Features and availability may
            change without notice.
          </p>

          <h2 className="mt-6 text-xl font-semibold text-heading">User Responsibilities</h2>
          <p>
            Do not use the service to process malicious, illegal, or harmful content. The input
            field is for mathematical problems only. You are responsible for verifying answers
            before relying on them for academic or professional purposes.
          </p>

          <h2 className="mt-6 text-xl font-semibold text-heading">Disclaimer</h2>
          <p>
            Results may be generated by AI or local symbolic engines. While we strive for accuracy,
            we cannot guarantee that every solution is correct or complete. Always verify important
            answers independently.
          </p>

          <h2 className="mt-6 text-xl font-semibold text-heading">Termination</h2>
          <p>
            We may suspend or terminate access to the service for misuse, abuse, or violation of
            these terms at any time. Continued use after changes constitutes acceptance of the
            updated terms.
          </p>

          <h2 className="mt-6 text-xl font-semibold text-heading">Changes</h2>
          <p>
            We may update these terms at any time. Continued use of the service constitutes
            acceptance of the changes.
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
