export type WorkedCalculatorExample = {
  title: string;
  problem: string;
  method: string;
  steps: readonly string[];
  answer: string;
};

export type LearningLink = { label: string; href: string };

export type CalculatorQualityContent = {
  searchIntent: string;
  methodOverview: string;
  supportedProblems: readonly string[];
  limitations: readonly string[];
  workedExamples: readonly WorkedCalculatorExample[];
  relatedLearning: readonly LearningLink[];
  additionalFaqs: readonly { question: string; answer: string }[];
};

// These profiles are deliberately written for the mathematical intent of each
// flagship route. They are not generated by replacing a calculator name in a
// shared paragraph.
export const calculatorQualityContent: Readonly<Record<string, CalculatorQualityContent>> = {
  "derivative-calculator": {
    searchIntent: "Find a derivative with this calculator and understand which differentiation rule applies at each stage.",
    methodOverview: "The calculator classifies sums, products, quotients, powers, and compositions before applying the matching differentiation rules. The result is simplified and can be checked by differentiating equivalent forms or comparing numerical slopes.",
    supportedProblems: ["Polynomial, rational, trigonometric, exponential, and logarithmic functions", "Product, quotient, and chain-rule combinations", "First and higher-order derivatives with respect to x"],
    limitations: ["Piecewise functions and implicit equations may require a more explicit input format.", "A simplified symbolic answer can look different from an equivalent textbook form."],
    workedExamples: [
      { title: "Power rule", problem: "Differentiate x^4 - 3x^2 + 2", method: "Differentiate each term.", steps: ["Apply d(x^n)/dx = n x^(n-1) to each power.", "The derivative of the constant 2 is 0.", "Combine the resulting terms."], answer: "4x^3-6x" },
      { title: "Product rule", problem: "Differentiate x^2 sin(x)", method: "Use (uv)' = u'v + uv'.", steps: ["Let u=x^2 and v=sin(x).", "Compute u'=2x and v'=cos(x).", "Substitute into the product rule."], answer: "2x\sin(x)+x^2\cos(x)" },
      { title: "Chain rule", problem: "Differentiate e^(3x^2)", method: "Differentiate the outer exponential and then the inner exponent.", steps: ["Set u=3x^2.", "The outer derivative is e^u and du/dx=6x.", "Multiply the outer and inner derivatives."], answer: "6xe^{3x^2}" }
    ],
    relatedLearning: [{ label: "Derivative rules guide", href: "/guides/derivative-rules" }, { label: "Derivative examples", href: "/examples/derivative-polynomial" }, { label: "Second derivative example", href: "/examples/second-derivative" }, { label: "Calculus Calculator", href: "/calculus-calculator" }],
    additionalFaqs: [{ question: "How should I enter a composite function?", answer: "Use parentheses around the inner expression, for example exp(3*x^2) or sin(x^2+1)." }, { question: "How can I check a derivative?", answer: "Differentiate an equivalent form, inspect the rules used, or compare the result with numerical slopes at valid sample points." }]
  },
  "integral-calculator": {
    searchIntent: "Find an antiderivative and learn why a substitution, identity, or integration rule works.",
    methodOverview: "The calculator first looks for linearity and standard antiderivatives, then considers substitution, products, and common trigonometric or exponential patterns. Indefinite integrals include a constant because many functions share the same derivative.",
    supportedProblems: ["Polynomial and power-function antiderivatives", "Common trigonometric, exponential, and logarithmic integrands", "Basic substitution and integration-by-parts patterns"],
    limitations: ["Some elementary-looking integrals have no elementary antiderivative.", "Always distinguish an indefinite integral from one with numeric bounds."],
    workedExamples: [
      { title: "Reverse power rule", problem: "Integrate 3x^2 - 4x", method: "Increase each exponent by one and divide by the new exponent.", steps: ["Integrate 3x^2 to obtain x^3.", "Integrate -4x to obtain -2x^2.", "Add the constant of integration."], answer: "x^3-2x^2+C" },
      { title: "Substitution", problem: "Integrate 2x cos(x^2)", method: "Use u=x^2.", steps: ["Let u=x^2, so du=2x dx.", "Rewrite the integral as the integral of cos(u).", "Integrate and substitute x^2 back for u."], answer: "\sin(x^2)+C" },
      { title: "Integration by parts", problem: "Integrate x e^x", method: "Use integration by parts with u=x.", steps: ["Choose u=x and dv=e^x dx.", "Then du=dx and v=e^x.", "Apply uv minus the integral of v du."], answer: "e^x(x-1)+C" }
    ],
    relatedLearning: [{ label: "Integration basics guide", href: "/guides/integration-basics" }, { label: "Integration by parts example", href: "/examples/integral-by-parts" }, { label: "Definite integral example", href: "/examples/definite-integral" }],
    additionalFaqs: [{ question: "Why does an indefinite integral need +C?", answer: "Differentiation removes constants, so every antiderivative represents a family of functions differing by a constant." }, { question: "What if the antiderivative is not elementary?", answer: "The calculator may return a special-function form or explain that a numerical method or advanced representation is needed." }]
  },
  "definite-integral-calculator": {
    searchIntent: "Evaluate an integral between two bounds and see how endpoint substitution produces the exact value.",
    methodOverview: "A definite integral is evaluated by finding an antiderivative when possible and applying F(b)-F(a). The sign records net accumulation, so area below the x-axis contributes negatively unless total geometric area is requested.",
    supportedProblems: ["Exact polynomial and elementary-function integrals", "Finite lower and upper bounds", "Signed accumulation over a closed interval"],
    limitations: ["An improper integral requires a limit and may diverge.", "Discontinuities inside the interval must be handled as separate improper integrals."],
    workedExamples: [
      { title: "Polynomial interval", problem: "Evaluate integral from 0 to 2 of x^2 dx", method: "Use the Fundamental Theorem of Calculus.", steps: ["An antiderivative is x^3/3.", "Evaluate it at 2 and at 0.", "Subtract the lower endpoint value."], answer: "\frac{8}{3}" },
      { title: "Trigonometric interval", problem: "Evaluate integral from 0 to pi of sin(x) dx", method: "Use -cos(x) as an antiderivative.", steps: ["Find F(x)=-cos(x).", "Compute F(pi)=1 and F(0)=-1.", "Subtract to obtain 2."], answer: "2" },
      { title: "Reversed bounds", problem: "Evaluate integral from 3 to 1 of 2x dx", method: "Keep the bound order when applying F(b)-F(a).", steps: ["An antiderivative is x^2.", "Compute F(1)-F(3).", "The reversed interval makes the result negative."], answer: "-8" }
    ],
    relatedLearning: [{ label: "Integration basics guide", href: "/guides/integration-basics" }, { label: "Definite integral example", href: "/examples/definite-integral" }, { label: "Integral Calculator", href: "/integral-calculator" }],
    additionalFaqs: [{ question: "Should I add +C to a definite integral?", answer: "No. The constant cancels in F(b)-F(a), so a bounded integral has a numeric or exact expression as its result." }, { question: "Can a definite integral be negative?", answer: "Yes. It measures signed accumulation; portions below the axis count negatively." }]
  },
  "limit-calculator": {
    searchIntent: "Evaluate nearby behavior at a point or at infinity and understand how an indeterminate form is resolved.",
    methodOverview: "The calculator tries direct substitution first. If that produces an indeterminate form, it simplifies algebraically or applies a suitable standard limit, while one-sided behavior is checked near discontinuities.",
    supportedProblems: ["Finite and infinite limits", "Rational, trigonometric, exponential, and logarithmic expressions", "Removable discontinuities and one-sided behavior"],
    limitations: ["A two-sided limit does not exist when the left and right limits disagree.", "Oscillatory expressions may remain without a single limiting value."],
    workedExamples: [
      { title: "Removable discontinuity", problem: "Limit of (x^2-1)/(x-1) as x approaches 1", method: "Factor before substituting.", steps: ["Direct substitution gives 0/0.", "Factor x^2-1 as (x-1)(x+1).", "Cancel for nearby x and evaluate x+1 at 1."], answer: "2" },
      { title: "Standard trigonometric limit", problem: "Limit of sin(x)/x as x approaches 0", method: "Use the fundamental sine limit.", steps: ["Recognize the 0/0 form.", "Apply the standard limit in radians.", "Conclude the nearby ratio approaches 1."], answer: "1" },
      { title: "Behavior at infinity", problem: "Limit of (3x^2+1)/(x^2-4) as x approaches infinity", method: "Compare the highest powers.", steps: ["Divide numerator and denominator by x^2.", "Terms containing 1/x^2 approach zero.", "Take the ratio of leading coefficients."], answer: "3" }
    ],
    relatedLearning: [{ label: "Understanding limits guide", href: "/guides/understanding-limits" }, { label: "Sine limit example", href: "/examples/limit-sinc" }, { label: "Asymptote Calculator", href: "/asymptote-calculator" }],
    additionalFaqs: [{ question: "Does 0/0 mean the limit is zero?", answer: "No. It is an indeterminate form that signals the expression needs simplification or another limiting method." }, { question: "When does a two-sided limit fail to exist?", answer: "It fails when either one-sided limit is missing or when the left and right limiting values are different." }]
  },
  "asymptote-calculator": {
    searchIntent: "Find vertical, horizontal, or slant asymptotes and distinguish them from removable holes.",
    methodOverview: "The calculator factors the expression, checks denominator zeros that remain after cancellation, and compares polynomial degrees for end behavior. A canceled denominator factor identifies a hole rather than a vertical asymptote.",
    supportedProblems: ["Vertical asymptotes of rational functions", "Horizontal asymptotes from end behavior", "Slant asymptotes from polynomial division"],
    limitations: ["A denominator zero is not automatically an asymptote if its factor cancels.", "Non-rational functions may need separate limit analysis."],
    workedExamples: [
      { title: "Vertical asymptote", problem: "Find asymptotes of 1/(x-2)", method: "Set the uncanceled denominator equal to zero.", steps: ["The denominator vanishes at x=2.", "No numerator factor cancels x-2.", "The function grows without bound near x=2."], answer: "x=2,\ y=0" },
      { title: "Horizontal asymptote", problem: "Find the horizontal asymptote of (2x+1)/(x-3)", method: "Compare equal polynomial degrees.", steps: ["Both numerator and denominator have degree 1.", "Use the ratio of leading coefficients 2/1.", "The end behavior approaches y=2."], answer: "y=2" },
      { title: "Hole versus asymptote", problem: "Analyze (x^2-1)/(x-1)", method: "Factor and cancel before classifying denominator zeros.", steps: ["Factor the numerator as (x-1)(x+1).", "Cancel x-1 for x not equal to 1.", "The missing point is a hole at (1,2), not a vertical asymptote."], answer: "\text{hole at }(1,2)" }
    ],
    relatedLearning: [{ label: "Understanding limits guide", href: "/guides/understanding-limits" }, { label: "Limit Calculator", href: "/limit-calculator" }, { label: "Graphing functions guide", href: "/guides/graphing-functions" }],
    additionalFaqs: [{ question: "Is every denominator zero a vertical asymptote?", answer: "No. First factor and simplify; a canceled factor creates a removable hole instead." }, { question: "Can a graph cross a horizontal asymptote?", answer: "Yes. A horizontal asymptote describes end behavior and does not prevent crossings at finite x-values." }]
  },
  "gradient-calculator": {
    searchIntent: "Compute a gradient vector and understand how each partial derivative contributes to direction of change.",
    methodOverview: "The gradient is assembled by differentiating once with respect to each independent variable while holding the others constant. At a point, the vector points in the direction of steepest local increase.",
    supportedProblems: ["Two-variable and common multivariable scalar functions", "Symbolic first partial derivatives", "Gradient evaluation at specified points"],
    limitations: ["The gradient applies to scalar-valued functions, not directly to vector fields.", "A zero gradient marks a critical point but does not by itself classify it."],
    workedExamples: [
      { title: "Polynomial gradient", problem: "Find the gradient of x^2+y^2", method: "Differentiate with respect to each variable separately.", steps: ["Holding y constant gives f_x=2x.", "Holding x constant gives f_y=2y.", "Place both partials in a vector."], answer: "\nabla f=\langle2x,2y\rangle" },
      { title: "Mixed term", problem: "Find the gradient of xy+y^2", method: "Treat the other variable as constant in each partial.", steps: ["With respect to x, xy differentiates to y.", "With respect to y, xy+y^2 differentiates to x+2y.", "Assemble the ordered components."], answer: "\langle y,x+2y\rangle" },
      { title: "Evaluate at a point", problem: "Evaluate grad(x^2+y^2) at (1,-2)", method: "Find the symbolic gradient before substituting.", steps: ["The gradient is <2x,2y>.", "Substitute x=1 and y=-2.", "Evaluate each component."], answer: "\langle2,-4\rangle" }
    ],
    relatedLearning: [{ label: "Multivariable calculus guide", href: "/guides/gradients-and-multivariable-calculus" }, { label: "Derivative Calculator", href: "/derivative-calculator" }, { label: "Graphing Calculator", href: "/graphing-calculator" }],
    additionalFaqs: [{ question: "Why is a gradient a vector?", answer: "It stores one partial derivative for each input direction, so both magnitude and direction matter." }, { question: "What does a zero gradient mean?", answer: "It identifies a critical point; additional tests are needed to determine whether it is a minimum, maximum, or saddle point." }]
  },
  "graphing-calculator": {
    searchIntent: "Plot a function and connect its formula with intercepts, domain, transformations, and end behavior.",
    methodOverview: "The calculator samples valid points across the viewing window and plots the resulting curve. A reliable interpretation also checks domain restrictions, intercepts, discontinuities, and whether the chosen window hides important behavior.",
    supportedProblems: ["Polynomial, rational, trigonometric, exponential, and logarithmic graphs", "Adjustable real-variable viewing windows", "Visual inspection of roots, turning points, and discontinuities"],
    limitations: ["A finite plot window cannot prove global behavior.", "Near asymptotes, connected sample points can look misleading unless domain breaks are considered."],
    workedExamples: [
      { title: "Quadratic graph", problem: "Graph y=x^2-4x+3", method: "Use factoring and completing the square to predict key points.", steps: ["Factor to find x-intercepts 1 and 3.", "Rewrite as (x-2)^2-1 for vertex (2,-1).", "Plot an upward-opening symmetric parabola."], answer: "\text{vertex }(2,-1),\ x=1,3" },
      { title: "Reciprocal graph", problem: "Graph y=1/x", method: "Identify domain and asymptotes before plotting.", steps: ["x=0 is excluded from the domain.", "Both axes are asymptotes.", "Plot branches in quadrants I and III."], answer: "x=0,\ y=0\text{ asymptotes}" },
      { title: "Sine transformation", problem: "Graph y=2 sin(x)", method: "Scale the parent sine graph vertically.", steps: ["The period remains 2pi.", "The amplitude changes from 1 to 2.", "Zeros remain at integer multiples of pi."], answer: "\text{amplitude }2,\ \text{period }2\pi" }
    ],
    relatedLearning: [{ label: "Graphing functions guide", href: "/guides/graphing-functions" }, { label: "Parabola example", href: "/examples/graph-parabola" }, { label: "Asymptote Calculator", href: "/asymptote-calculator" }],
    additionalFaqs: [{ question: "Why can a graphing window be misleading?", answer: "A narrow window may hide intercepts, turning points, or end behavior; inspect the formula and adjust the range." }, { question: "Does a graph prove the exact roots?", answer: "No. A graph estimates their location; use an equation solver for exact or verified numerical roots." }]
  },
  "algebra-solver": {
    searchIntent: "Solve or transform an algebra problem while seeing the legal operation used at each step.",
    methodOverview: "The solver identifies whether the input is an equation or an expression, then selects equation solving, factoring, expansion, or simplification. Proposed solutions are checked in the original equation whenever verification is available.",
    supportedProblems: ["Linear and quadratic equations", "Polynomial factoring and expansion", "Simplification of common algebraic expressions"],
    limitations: ["An expression without an equals sign is simplified rather than solved for a variable.", "Domain restrictions from denominators and radicals must be retained."],
    workedExamples: [
      { title: "Linear equation", problem: "Solve 2x+5=17", method: "Undo operations while keeping both sides equal.", steps: ["Subtract 5 from both sides.", "Divide both sides by 2.", "Substitute x=6 into the original equation to verify."], answer: "x=6" },
      { title: "Factor a quadratic", problem: "Factor x^2-9", method: "Recognize a difference of squares.", steps: ["Write 9 as 3^2.", "Apply a^2-b^2=(a-b)(a+b).", "Expand the factors to check."], answer: "(x-3)(x+3)" },
      { title: "Simplify a rational expression", problem: "Simplify (x^2-1)/(x-1)", method: "Factor before canceling.", steps: ["Factor x^2-1 as (x-1)(x+1).", "Cancel the common factor when x is not 1.", "Keep the original restriction x not equal to 1."], answer: "x+1,\quad x\ne1" }
    ],
    relatedLearning: [{ label: "Solving equations guide", href: "/guides/solving-equations" }, { label: "Factoring guide", href: "/guides/factoring-polynomials" }, { label: "Algebra examples", href: "/examples/linear-equation" }],
    additionalFaqs: [{ question: "What is the difference between solve and simplify?", answer: "Solving finds values that make an equation true; simplifying rewrites an expression in an equivalent, usually shorter form." }, { question: "How are algebra answers checked?", answer: "When possible, each proposed solution is substituted into the original equation rather than only checking a transformed form." }]
  },
  "equation-solver": {
    searchIntent: "Solve for an unknown and verify which candidate values satisfy the original equation.",
    methodOverview: "The solver classifies the equation by degree and structure, applies reversible operations or a suitable polynomial method, and checks candidate roots in the original input to catch extraneous solutions.",
    supportedProblems: ["Linear and quadratic equations", "Common polynomial and rational equations", "Single-variable equations with exact or numerical roots"],
    limitations: ["Squaring or clearing denominators can introduce candidates that must be rejected.", "Some transcendental equations require numerical approximations."],
    workedExamples: [
      { title: "One-step isolation", problem: "Solve 3x-7=11", method: "Use inverse operations.", steps: ["Add 7 to both sides to get 3x=18.", "Divide both sides by 3.", "Check that 3(6)-7 equals 11."], answer: "x=6" },
      { title: "Quadratic roots", problem: "Solve x^2-5x+6=0", method: "Factor the quadratic.", steps: ["Find two numbers with product 6 and sum -5.", "Write (x-2)(x-3)=0.", "Apply the zero-product property."], answer: "x=2\text{ or }x=3" },
      { title: "Rational restriction", problem: "Solve (x+1)/(x-2)=2", method: "Record the denominator restriction before clearing it.", steps: ["Require x not equal to 2.", "Multiply by x-2 to get x+1=2x-4.", "Solve x=5 and verify it is allowed."], answer: "x=5" }
    ],
    relatedLearning: [{ label: "Solving equations guide", href: "/guides/solving-equations" }, { label: "Linear equation example", href: "/examples/linear-equation" }, { label: "Quadratic equation example", href: "/examples/quadratic-equation" }],
    additionalFaqs: [{ question: "Why can an equation have an extraneous solution?", answer: "Non-reversible operations such as squaring can create candidates, so they must be checked in the original equation." }, { question: "Can the result be an approximation?", answer: "Yes. Equations without a convenient symbolic form may be solved numerically and clearly marked as approximate." }]
  },
  "quadratic-solver": {
    searchIntent: "Find all roots of a quadratic and understand whether factoring, completing the square, or the quadratic formula is appropriate.",
    methodOverview: "The solver converts the equation to ax^2+bx+c=0, checks whether it factors cleanly, and otherwise applies the quadratic formula. The discriminant determines how many real roots exist.",
    supportedProblems: ["Quadratics with real or complex roots", "Factoring and quadratic-formula solutions", "Exact radical and decimal root forms"],
    limitations: ["The leading coefficient a must be nonzero for the equation to be quadratic.", "Decimal coefficients can make an exact factored form less convenient."],
    workedExamples: [
      { title: "Factorable quadratic", problem: "Solve x^2-5x+6=0", method: "Factor using product and sum.", steps: ["Find -2 and -3 because their product is 6 and sum is -5.", "Write (x-2)(x-3)=0.", "Set each factor equal to zero."], answer: "x=2,3" },
      { title: "Repeated root", problem: "Solve x^2-6x+9=0", method: "Recognize a perfect-square trinomial.", steps: ["The expression factors as (x-3)^2.", "Set x-3 equal to zero.", "The discriminant is zero, confirming one repeated root."], answer: "x=3" },
      { title: "Complex roots", problem: "Solve x^2+4=0", method: "Isolate x^2 and use i^2=-1.", steps: ["Move 4 to obtain x^2=-4.", "Take both square roots.", "Write sqrt(-4) as 2i."], answer: "x=\pm2i" }
    ],
    relatedLearning: [{ label: "Solving equations guide", href: "/guides/solving-equations" }, { label: "Quadratic example", href: "/examples/quadratic-equation" }, { label: "Factoring Calculator", href: "/factoring-calculator" }],
    additionalFaqs: [{ question: "What does the discriminant tell me?", answer: "A positive discriminant gives two real roots, zero gives one repeated real root, and a negative value gives two complex roots." }, { question: "Why does the quadratic formula always work?", answer: "It comes from completing the square on the general equation ax^2+bx+c=0, so it applies to every quadratic with a nonzero a." }]
  },
  "factoring-calculator": {
    searchIntent: "Rewrite a polynomial as a product and see which common factor or identity makes the factorization possible.",
    methodOverview: "The calculator checks the greatest common factor first, then standard identities, trinomial patterns, and grouping. A factorization is verified by expanding the product back to the original expression.",
    supportedProblems: ["Greatest-common-factor extraction", "Difference of squares and perfect-square identities", "Common quadratic and polynomial factorizations"],
    limitations: ["Some polynomials are irreducible over the requested number system.", "Factoring over real numbers can differ from factoring over complex numbers."],
    workedExamples: [
      { title: "Greatest common factor", problem: "Factor 6x^3+9x^2", method: "Extract the largest shared numerical and variable factor.", steps: ["The numerical GCF of 6 and 9 is 3.", "Both terms contain x^2.", "Divide each term by 3x^2 to form the remaining binomial."], answer: "3x^2(2x+3)" },
      { title: "Difference of squares", problem: "Factor x^2-16", method: "Use a^2-b^2.", steps: ["Recognize 16 as 4^2.", "Apply (a-b)(a+b).", "Expand to verify the middle terms cancel."], answer: "(x-4)(x+4)" },
      { title: "Quadratic trinomial", problem: "Factor x^2+7x+12", method: "Find two integers with product 12 and sum 7.", steps: ["List factor pairs of 12.", "Choose 3 and 4 because 3+4=7.", "Write the matching binomials."], answer: "(x+3)(x+4)" }
    ],
    relatedLearning: [{ label: "Factoring polynomials guide", href: "/guides/factoring-polynomials" }, { label: "Difference of squares example", href: "/examples/factor-difference-squares" }, { label: "Quadratic Solver", href: "/quadratic-solver" }],
    additionalFaqs: [{ question: "How do I check a factorization?", answer: "Expand the proposed factors and confirm that every coefficient matches the original polynomial." }, { question: "Why should I check the GCF first?", answer: "Removing the GCF exposes the simpler remaining pattern and prevents an incomplete factorization." }]
  },
  "simplify-calculator": {
    searchIntent: "Rewrite an expression in an equivalent simpler form without losing domain restrictions.",
    methodOverview: "The calculator combines like terms, distributes or factors where useful, reduces rational expressions by common factors, and preserves restrictions inherited from the original expression.",
    supportedProblems: ["Combining like terms and distributing products", "Polynomial and rational-expression simplification", "Basic exponent and radical reductions"],
    limitations: ["Equivalent expressions may have different appearances.", "Canceling a factor does not remove restrictions from the original denominator."],
    workedExamples: [
      { title: "Combine like terms", problem: "Simplify 3x+2x-4", method: "Add coefficients of terms with the same variable part.", steps: ["Identify 3x and 2x as like terms.", "Add their coefficients to get 5x.", "Keep the constant -4."], answer: "5x-4" },
      { title: "Distribute and combine", problem: "Simplify 2(x+3)-x", method: "Distribute before combining like terms.", steps: ["Multiply 2 by both terms in parentheses.", "Rewrite as 2x+6-x.", "Combine the x terms."], answer: "x+6" },
      { title: "Rational expression", problem: "Simplify (x^2-1)/(x-1)", method: "Factor numerator and cancel a common factor.", steps: ["Factor the numerator as (x-1)(x+1).", "Cancel x-1 when it is nonzero.", "State the original restriction x not equal to 1."], answer: "x+1,\quad x\ne1" }
    ],
    relatedLearning: [{ label: "Simplifying expressions guide", href: "/guides/simplifying-expressions" }, { label: "Rational-expression example", href: "/examples/simplify-rational" }, { label: "Factoring Calculator", href: "/factoring-calculator" }],
    additionalFaqs: [{ question: "Can two different-looking answers both be correct?", answer: "Yes. Expanding, factoring, and applying identities can produce equivalent forms; evaluate or transform them to compare." }, { question: "Why must denominator restrictions remain?", answer: "Simplification cannot make an input valid at a value where the original expression was undefined." }]
  }
};
