import type { FaqItem } from "@/components/marketing/faq";

export const calculusFaqs: FaqItem[] = [
  {
    question: "What calculus operations are supported?",
    answer:
      "Calculus Solver supports derivatives, higher-order derivatives, indefinite and definite integrals, limits, and function graphing."
  },
  {
    question: "Does the solver show integration constants?",
    answer:
      "Yes. Indefinite integrals include +C in the answer and the steps explain why the constant is needed."
  },
  {
    question: "How are limits verified?",
    answer:
      "Limits are difficult to verify symbolically in the browser. We mark them as partially verified and use numerical sampling as a sanity check."
  },
  {
    question: "Is Calculus Solver free?",
    answer:
      "Yes. The core solver is free to use directly in your browser with no subscription required."
  },
  {
    question: "Do I need an account?",
    answer:
      "No. Calculus Solver does not require an account or login. Your history is stored locally in your browser."
  },
  {
    question: "Can I use it on mobile?",
    answer:
      "Yes. The interface is responsive and works on phones, tablets, and desktops."
  },
  {
    question: "How accurate are the answers?",
    answer:
      "Answers are generated by a combination of AI reasoning and local symbolic verification. We recommend independently checking important results."
  }
];

export const algebraFaqs: FaqItem[] = [
  {
    question: "What algebra operations are supported?",
    answer:
      "Algebra Solver supports solving linear and quadratic equations, systems of equations, factoring, expanding, simplifying, and inequalities."
  },
  {
    question: "How do I enter a system of equations?",
    answer:
      "Write both equations in one line connected by 'and', for example: 'Solve x + y = 5 and x − y = 1'."
  },
  {
    question: "Are the solutions verified?",
    answer:
      "Yes. For equations, the solver substitutes solutions back into the original equation and reports the verification status."
  },
  {
    question: "Is Calculus Solver free?",
    answer:
      "Yes. The core solver is free to use directly in your browser with no subscription required."
  },
  {
    question: "Do I need an account?",
    answer:
      "No. Calculus Solver does not require an account or login. Your history is stored locally in your browser."
  },
  {
    question: "Can I use it on mobile?",
    answer:
      "Yes. The interface is responsive and works on phones, tablets, and desktops."
  },
  {
    question: "How accurate are the answers?",
    answer:
      "Answers are generated by a combination of AI reasoning and local symbolic verification. We recommend independently checking important results."
  }
];

export const generalFaqs: FaqItem[] = [
  {
    question: "What is a calculus solver?",
    answer:
      "A calculus solver is an online math tool that interprets calculus problems, computes the result, and explains the rules and intermediate steps used to reach the answer."
  },
  {
    question: "Can Calculus Solver show steps?",
    answer:
      "Yes. Calculus Solver separates the answer from the step-by-step solution so you can review each transformation and understand why it is valid."
  },
  {
    question: "Is Calculus Solver free?",
    answer:
      "Yes. You can enter calculus problems and review the generated answer and explanation without creating an account."
  },
  {
    question: "Can it solve derivatives?",
    answer:
      "Yes. It can solve common first and higher-order derivatives and explain rules such as the power, product, quotient, and chain rules."
  },
  {
    question: "Can it solve integrals?",
    answer:
      "Yes. It supports common indefinite and definite integrals, shows the integration method, and includes the constant of integration when required."
  },
  {
    question: "Can it evaluate limits?",
    answer:
      "Yes. Enter the expression, the variable, and the value being approached. The solver can evaluate many finite, infinite, and one-sided limits."
  },
  {
    question: "How should I enter a calculus problem?",
    answer:
      "Use ordinary keyboard notation or the math keyboard. For example, enter d/dx x^2, integrate x^2, or limit sin(x)/x as x approaches 0."
  },
  {
    question: "How are answers checked?",
    answer:
      "When possible, results are checked symbolically or by substituting them back into the original problem. The result panel reports the available verification status."
  }
];
