import type { FaqItem } from "@/components/marketing/faq";

export const calculusFaqs: FaqItem[] = [
  {
    question: "What calculus operations are supported?",
    answer:
      "Calculus Solver supports derivatives, higher-order derivatives, indefinite and definite integrals, limits, and function graphing."
  },
  {
    question: "Does the solver show integration constants?",
    answer:
      "Yes. Indefinite integrals include +C in the answer and the steps explain why the constant is needed."
  },
  {
    question: "How are limits verified?",
    answer:
      "Limits are difficult to verify symbolically in the browser. We mark them as partially verified and use numerical sampling as a sanity check."
  },
  {
    question: "Is Calculus Solver free?",
    answer:
      "Yes. The core solver is free to use directly in your browser with no subscription required."
  },
  {
    question: "Do I need an account?",
    answer:
      "No. Calculus Solver does not require an account or login. Your history is stored locally in your browser."
  },
  {
    question: "Can I use it on mobile?",
    answer:
      "Yes. The interface is responsive and works on phones, tablets, and desktops."
  },
  {
    question: "How accurate are the answers?",
    answer:
      "Answers are generated by a combination of AI reasoning and local symbolic verification. We recommend independently checking important results."
  }
];

export const algebraFaqs: FaqItem[] = [
  {
    question: "What algebra operations are supported?",
    answer:
      "Algebra Solver supports solving linear and quadratic equations, systems of equations, factoring, expanding, simplifying, and inequalities."
  },
  {
    question: "How do I enter a system of equations?",
    answer:
      "Write both equations in one line connected by 'and', for example: 'Solve x + y = 5 and x − y = 1'."
  },
  {
    question: "Are the solutions verified?",
    answer:
      "Yes. For equations, the solver substitutes solutions back into the original equation and reports the verification status."
  },
  {
    question: "Is Calculus Solver free?",
    answer:
      "Yes. The core solver is free to use directly in your browser with no subscription required."
  },
  {
    question: "Do I need an account?",
    answer:
      "No. Calculus Solver does not require an account or login. Your history is stored locally in your browser."
  },
  {
    question: "Can I use it on mobile?",
    answer:
      "Yes. The interface is responsive and works on phones, tablets, and desktops."
  },
  {
    question: "How accurate are the answers?",
    answer:
      "Answers are generated by a combination of AI reasoning and local symbolic verification. We recommend independently checking important results."
  }
];

export const generalFaqs: FaqItem[] = [
  {
    question: "What is Calculus Solver?",
    answer:
      "Calculus Solver is an AI-powered math assistant that solves calculus and algebra problems with step-by-step explanations, LaTeX rendering, and interactive graphs."
  },
  {
    question: "Is Calculus Solver free?",
    answer:
      "Yes. The core solver is free to use directly in your browser with no subscription required."
  },
  {
    question: "Do I need an account?",
    answer:
      "No. Calculus Solver does not require an account or login. Your history is stored locally in your browser."
  },
  {
    question: "Can I use it on mobile?",
    answer:
      "Yes. The interface is responsive and works on phones, tablets, and desktops."
  },
  {
    question: "How accurate are the answers?",
    answer:
      "Answers are generated by a combination of AI reasoning and local symbolic verification. We recommend independently checking important results."
  }
];
